version: 2.1

orbs:
  tools: replikativ/clj-tools@0

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: docker-deploy
      - tools/format:
          context: docker-deploy
          requires:
            - tools/setup
      - build-and-test:
          context: docker-deploy
          requires:
            - tools/setup
      - tools/deploy:
          context:
            - clojars-deploy
            - docker-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/setup
            - build-and-test
      - tools/release:
          context:
            - github-token
            - docker-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/deploy

jobs:
  build-and-test:
    docker:
      - image: cimg/clojure:1.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies-
      - run:
          name: Download dependencies
          command: clojure -P -M:test:build
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run:
          name: Compile Java sources
          command: clojure -T:build compile-java
      - run:
          name: Run tests
          command: clojure -M:test
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .m2
